server:
  port: 83

spring:
  application:
    name: nacos-consumer-order
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'
#消费者将要去访问的微服务名称
server-url:
  nacos-user-service: http://nacos-payment-provider